### ISSUE TITLE
💩! €200 for ☃ day

### ISSUE THREAD

**Issue by rdebath** [sbenstewart/text-to-brainfuck#3]
Unicode characters don't convert very well. For example the string `💩! €200 for ☃ day`

Firstly the encoding appears to be direct Unicode the `€` character prints character 8364. While this isn't completely wrong, most interpreters will use UTF-8 not direct Unicode.

Then the code generation cannot really cope, the `€` the `☃` characters give around 800 and 900 pluses each! I would guess a size of a few hundred BF commands for the whole string. 

The `💩` emoji has another problem; it outputs two values: 55357 and 56489, this shows that it's not using direct Unicode, instead it's using UTF-16. It also outputs over 10000 pluses for that one character.

**Comment by sbenstewart** [comment]
@rdebath I'll look into this very long problem. Any pointers or suggestions, before I deep dive into coding the fix ?

**Comment by rdebath** [comment]
Well, for big numbers I'd suggest something like a power series ... https://esolangs.org/wiki/Brainfuck_constants#Algorithms

Unfortunately, the UTF-16 is a problem with Javascript. Unlike (for example) Python which, I think, fixed it's UTF-16 issue when going from V2 to V3, Javascript has not changed anything since UCS-2/UTF-16 was baked into it in the '90s. So your only option at that point seems to be to decode the UTF-16 surrogates manually.

OTOH If you want to switch to UTF-8 there are the old `escape` and `unescape` javascript function, but they're deprecated ...
so perhaps a function using `encodeURIcomponent` like https://github.com/quicbit-js/qb-utf8-from-str-tiny

**Comment by sbenstewart** [comment]
Seems the APIs for `encodeURIComponent` and `decodeURIComponent` really do work.

Have pushed a commit https://github.com/sbenstewart/text-to-brainfuck/commit/920095ce139ad7f8881804e436e6bd2b35acc12b for the same.

Do check if the commit resolves the issue.

**Comment by rdebath** [comment]
Looks pretty reasonable to me.
``` bf
++++++++++[>++++++++++++++++++++++++>++++++++++++++++>+++++++++++++++>++++
+++++++++++++>+++>+++++++++++++++++++++++>+++++++++++++>+++++>++++++++++>+
++++++++++>++++++++++++<<<<<<<<<<<-]>.>-.>----.>-.>+++.-.>----.>.<<<+++.>>
>>.--..<<<.>>>>++.>+.+++.<<<<<.>.<<<++++++.>>>>+.<<.>>>>--.---.>>+.
```
Two cells.
``` bf
+++++[->++++++<]>[-<++++++++>]<.[--->++<]>-.-------------.-<++++++[>++++<-
]>.+[-----<+>]<-.-.[->+++++++<]>++.-[-----<+++>]<-----.-[--->++++<]>.[----
<+>]<+++++++.--..[--->++<]>.++[-<+++>]<.+++++++++.+++.[--->+<]>------.[-<+
++++++>]<++.++[--->++<]>.<+++++++[>---<-]>.+[----<+>]<-.+[->+++<]>+.---.-[
----<+++++>]<+.
```
Brute force multiply loop
``` bf
>++++++++[<++++>-]<+[>+++++++>+++++>++++>+++++>+++++++>+>+>+++>+++<<<<<<<<
<-]>+++++++++.>------.-------------.>>++++.>>.-.<-----.<<--.>+++.>>+++++++
+++++++++++.--..>-.>+++.+++++++++.+++.<.<<.<<<++++++.>+.>>>>.>>+.---.<++++
+++.
```

**Comment by sbenstewart** [comment]
So do we close this issue ?
